#!/bin/bash

if [ ! -f /proc/device-tree/model ]; then
	exit 0
fi

model=$(tr -d '\0' < /proc/device-tree/model)

if [ "$model" = "Bananapi BPI-R2" ]; then
	ip link set eth0 down
	ip link set wan down
	ip link set lan0 down
	ip link set lan1 down
	ip link set lan2 down
	ip link set lan3 down
	ip link set eth0 name dsa
	ip link set wan name eth0
	ip link set lan0 name eth1
	ip link set lan1 name eth2
	ip link set lan2 name eth3
	ip link set lan3 name eth4
	ip link set dsa up
fi

exit 0
